# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feGDq4A2DggQkYRGIlXzxdG9MxUbXYww
"""

!pip install streamlit
!pip install geopandas
!pip install scikit-learn
!pip install folium
!pip install streamlit-folium

import streamlit as st
import pandas as pd
import geopandas as gpd
from sklearn.cluster import DBSCAN
import numpy as np
import folium
from streamlit_folium import st_folium
from folium.plugins import HeatMap

# 1. ตั้งค่าหน้าเว็บให้กว้างและดูสวยงาม
st.set_page_config(page_title="Pathum Thani Accident Dashboard", layout="wide")

st.title("📍 ระบบวิเคราะห์จุดเสี่ยงอุบัติเหตุจังหวัดปทุมธานี")
st.markdown("---")

# 2. ฟังก์ชันโหลดและประมวลผลข้อมูล (ใส่ @st.cache_data เพื่อความเร็ว)
@st.cache_data
def process_data():
    # โหลดข้อมูลอุบัติเหตุ
    df = pd.read_csv('/content/accident_PT.csv')
    df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
    df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')
    df.dropna(subset=['LATITUDE', 'LONGITUDE'], inplace=True)

    # วิเคราะห์จุดเสี่ยง (DBSCAN)
    coords = df[['LATITUDE', 'LONGITUDE']].values
    epsilon = 0.1 / 6371.0088
    db = DBSCAN(eps=epsilon, min_samples=3, algorithm='ball_tree', metric='haversine').fit(np.radians(coords))
    df['cluster'] = db.labels_

    # สรุปข้อมูล Top 10 Hotspots
    def get_top_info(group):
        vehicle_modes = group['รถคันที่1'].mode()
        top_v = vehicle_modes.iloc[0] if not vehicle_modes.empty else "ไม่ระบุ"
        cause_modes = group['มูลเหตุสันนิษฐาน'].mode()
        top_c = cause_modes.iloc[0] if not cause_modes.empty else "ไม่ระบุ"
        return pd.Series({
            'LATITUDE': group['LATITUDE'].mean(),
            'LONGITUDE': group['LONGITUDE'].mean(),
            'count': group['cluster'].count(),
            'top_vehicle': top_v,
            'top_cause': top_c
        })

    hotspots = df[df['cluster'] != -1].groupby('cluster').apply(get_top_info)
    top_10 = hotspots.sort_values('count', ascending=False).head(10)

    # โหลด Shapefiles (ปรับ path ให้ตรงกับไฟล์ในโฟลเดอร์ของคุณ)
    roads = gpd.read_file('/content/drive-download-20260420T102534Z-3-001.zip').to_crs(epsg=4326)
    boundary = gpd.read_file('/content/drive-download-20260420T110322Z-3-001.zip').to_crs(epsg=4326)

    return df, top_10, roads, boundary

# เรียกใช้งานฟังก์ชัน
try:
    df, top_10_hotspots, roads, boundary = process_data()

    # 3. ส่วนการแสดงผล (Layout)
    col1, col2 = st.columns([7, 3]) # แบ่งหน้าจอ 70% และ 30%

    with col1:
        st.subheader("🗺️ แผนที่ความหนาแน่นและจุดวิกฤต")

        # สร้างแผนที่ Folium
        m = folium.Map(location=[14.0208, 100.5250], zoom_start=11)

        # เพิ่ม HeatMap
        heat_data = df[['LATITUDE', 'LONGITUDE']].values.tolist()
        HeatMap(heat_data, radius=15, blur=10, min_opacity=0.5).add_to(m)

        # เพิ่มขอบเขตจังหวัด
        folium.GeoJson(boundary, name='ขอบเขตจังหวัด',
                       style_function=lambda x: {'fillColor': '#ffffff', 'color': 'black', 'weight': 2, 'fillOpacity': 0.1}).add_to(m)

        # เพิ่มถนน
        folium.GeoJson(roads, name='ถนน',
                       style_function=lambda x: {'color': '#3388ff', 'weight': 1, 'opacity': 0.3}).add_to(m)

        # ปักหมุด Top 10
        for i, (idx, row) in enumerate(top_10_hotspots.iterrows()):
            popup_html = f"<b>อันดับ {i+1}</b><br>เกิดเหตุ: {int(row['count'])} ครั้ง<br>สาเหตุ: {row['top_cause']}"
            folium.Marker(
                location=[row['LATITUDE'], row['LONGITUDE']],
                popup=folium.Popup(popup_html, max_width=200),
                icon=folium.Icon(color='red', icon='info-sign')
            ).add_to(m)

        # แสดงแผนที่ในหน้าเว็บ
        st_folium(m, width="100%", height=600)

    with col2:
        st.subheader("🏆 10 อันดับจุดอันตราย")
        for i, (idx, row) in enumerate(top_10_hotspots.iterrows()):
            with st.expander(f"อันดับที่ {i+1} (เกิดเหตุ {int(row['count'])} ครั้ง)"):
                st.write(f"🚘 **รถที่เกิดเหตุ:** {row['top_vehicle']}")
                st.write(f"💡 **สาเหตุ:** {row['top_cause']}")
                st.write(f"📍 **พิกัด:** {row['LATITUDE']:.4f}, {row['LONGITUDE']:.4f}")

except Exception as e:
    st.error(f"เกิดข้อผิดพลาดในการโหลดข้อมูล: {e}")
    st.info("ตรวจสอบว่าไฟล์ข้อมูล (CSV, ZIP) อยู่ในโฟลเดอร์เดียวกับ app.py หรือไม่")