# -*- coding: utf-8 -*-
"""mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xvuJW_KoREsbvfOsKTDwPANHhIsp8Jf
"""

import pandas as pd
import geopandas as gpd
from sklearn.cluster import DBSCAN
import numpy as np
import folium
from folium.plugins import HeatMap  # นำเข้าปลั๊กอินสำหรับสร้าง Heatmap

# 1. โหลดข้อมูลอุบัติเหตุ
df = pd.read_csv('/content/accident_PT.csv') # Changed from pd.read_excel to pd.read_csv
df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')
df.dropna(subset=['LATITUDE', 'LONGITUDE'], inplace=True)

# 2. โหลด Shapefiles (ถนน และ ขอบเขตจังหวัด)
roads = gpd.read_file('/content/drive-download-20260420T102534Z-3-001.zip').to_crs(epsg=4326)
boundary = gpd.read_file('/content/drive-download-20260420T110322Z-3-001.zip').to_crs(epsg=4326)

# 3. วิเคราะห์จุดเสี่ยง (DBSCAN)
coords = df[['LATITUDE', 'LONGITUDE']].values
epsilon = 0.1 / 6371.0088
db = DBSCAN(eps=epsilon, min_samples=3, algorithm='ball_tree', metric='haversine').fit(np.radians(coords))
df['cluster'] = db.labels_

# 4. สรุปข้อมูล และเลือกเฉพาะ Top 10
def get_top_info(group):
    # Get mode for 'รถคันที่1' and handle cases where mode() returns an empty Series
    vehicle_modes = group['รถคันที่1'].mode()
    top_vehicle = vehicle_modes.iloc[0] if not vehicle_modes.empty else "ไม่ระบุ"

    # Get mode for 'มูลเหตุสันนิษฐาน' and handle cases where mode() returns an empty Series
    cause_modes = group['มูลเหตุสันนิษฐาน'].mode()
    top_cause = cause_modes.iloc[0] if not cause_modes.empty else "ไม่ระบุ"

    return pd.Series({
        'LATITUDE': group['LATITUDE'].mean(),
        'LONGITUDE': group['LONGITUDE'].mean(),
        'count': group['cluster'].count(),
        'top_vehicle': top_vehicle,
        'top_cause': top_cause
    })

hotspots = df[df['cluster'] != -1].groupby('cluster').apply(get_top_info)
top_10_hotspots = hotspots.sort_values('count', ascending=False).head(10)

# 5. สร้างแผนที่
m = folium.Map(location=[14.0208, 100.5250], zoom_start=11)

# --- [เพิ่ม] ส่วนของ HeatMap ---
# เตรียมข้อมูลพิกัด (Lat, Lon) สำหรับสร้าง Heatmap
heat_data = df[['LATITUDE', 'LONGITUDE']].values.tolist()
HeatMap(heat_data,
        name='Heatmap ความหนาแน่น',
        radius=15,
        blur=10,
        min_opacity=0.5,
        gradient={0.4: 'blue', 0.65: 'lime', 1: 'red'}
       ).add_to(m)

# --- เพิ่มขอบเขตจังหวัดปทุมธานี ---
folium.GeoJson(
    boundary,
    name='ขอบเขตจังหวัดปทุมธานี',
    style_function=lambda x: {
        'fillColor': '#ffffff',
        'color': 'black',
        'weight': 2,
        'fillOpacity': 0.1
    }
).add_to(m)

# --- เพิ่มโครงข่ายถนน ---
folium.GeoJson(
    roads,
    name='โครงข่ายถนน',
    style_function=lambda x: {'color': '#3388ff', 'weight': 1, 'opacity': 0.4}
).add_to(m)

# 6. ปักหมุดเฉพาะ Top 10
for i, (idx, row) in enumerate(top_10_hotspots.iterrows()):
    popup_text = f"""
    <div style=\"font-family: Tahoma; font-size: 12px; width: 220px;\">
        <h4 style=\"margin:0; color:red;\">อันดับที่ {i+1}</h4>
        <hr style=\"margin:5px 0;\">
        <b>จำนวนครั้ง:</b> {int(row['count'])} ครั้ง<br>
        <b>รถที่เกิดเหตุบ่อย:</b> {row['top_vehicle']}<br>
        <b>สาเหตุหลัก:</b> {row['top_cause']}
    </div>
    """
    folium.Marker(
        location=[row['LATITUDE'], row['LONGITUDE']],
        popup=folium.Popup(popup_text, max_width=250),
        icon=folium.Icon(color='darkred', icon='exclamation', prefix='fa')
    ).add_to(m)

folium.LayerControl().add_to(m)
m