# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feGDq4A2DggQkYRGIlXzxdG9MxUbXYww
"""

import streamlit as st
import pandas as pd
import geopandas as gpd
from sklearn.cluster import DBSCAN
import numpy as np
import folium
from streamlit_folium import st_folium
from folium.plugins import HeatMap

# 1. ตั้งค่าหน้าเว็บให้กว้างสวยงาม
st.set_page_config(page_title="จุดเสี่ยงอุบัติเหตุ ปทุมธานี", layout="wide")

st.title("📍 ระบบวิเคราะห์จุดเสี่ยงอุบัติเหตุจังหวัดปทุมธานี")
st.markdown("วิเคราะห์ข้อมูลจุดเสี่ยงด้วย DBSCAN Clustering และแสดงผลแบบ Heatmap")

# 2. ฟังก์ชันโหลดและประมวลผลข้อมูล (ใช้ Cache เพื่อให้เว็บเร็ว)
@st.cache_data
def load_data_and_analyze():
    # โหลด CSV (ชื่อไฟล์ต้องตรงกับที่อัปโหลดขึ้น GitHub)
    df = pd.read_csv('accident_PT.csv')
    df['LATITUDE'] = pd.to_numeric(df['LATITUDE'], errors='coerce')
    df['LONGITUDE'] = pd.to_numeric(df['LONGITUDE'], errors='coerce')
    df.dropna(subset=['LATITUDE', 'LONGITUDE'], inplace=True)

    # โหลด Shapefiles จากไฟล์ Zip
    roads = gpd.read_file('drive-download-20260420T102534Z-3-001.zip').to_crs(epsg=4326)
    boundary = gpd.read_file('drive-download-20260420T110322Z-3-001.zip').to_crs(epsg=4326)

    # วิเคราะห์จุดเสี่ยง (DBSCAN)
    coords = df[['LATITUDE', 'LONGITUDE']].values
    epsilon = 0.1 / 6371.0088
    db = DBSCAN(eps=epsilon, min_samples=3, algorithm='ball_tree', metric='haversine').fit(np.radians(coords))
    df['cluster'] = db.labels_

    # สรุปข้อมูล Top 10
    def get_top_info(group):
        vehicle_modes = group['รถคันที่1'].mode()
        top_vehicle = vehicle_modes.iloc[0] if not vehicle_modes.empty else "ไม่ระบุ"
        cause_modes = group['มูลเหตุสันนิษฐาน'].mode()
        top_cause = cause_modes.iloc[0] if not cause_modes.empty else "ไม่ระบุ"

        return pd.Series({
            'LATITUDE': group['LATITUDE'].mean(),
            'LONGITUDE': group['LONGITUDE'].mean(),
            'count': group['cluster'].count(),
            'top_vehicle': top_vehicle,
            'top_cause': top_cause
        })

    hotspots = df[df['cluster'] != -1].groupby('cluster').apply(get_top_info, include_groups=False)
    top_10 = hotspots.sort_values('count', ascending=False).head(10)

    return df, top_10, roads, boundary

# --- เริ่มการทำงาน ---
try:
    df, top_10_hotspots, roads, boundary = load_data_and_analyze()

    # สร้างคอลัมน์ซ้าย-ขวา (70% : 30%)
    col_map, col_info = st.columns([7, 3])

    with col_map:
        st.subheader("🗺️ แผนที่จุดเสี่ยงและ Heatmap")

        # 3. สร้างแผนที่ Folium
        m = folium.Map(location=[14.0208, 100.5250], zoom_start=11)

        # เพิ่ม HeatMap
        heat_data = df[['LATITUDE', 'LONGITUDE']].values.tolist()
        HeatMap(heat_data, radius=15, blur=10, min_opacity=0.5).add_to(m)

        # เพิ่ม GeoJson (ขอบเขตและถนน)
        folium.GeoJson(boundary, name='ขอบเขตจังหวัด',
                       style_function=lambda x: {'fillColor': '#ffffff', 'color': 'black', 'weight': 2, 'fillOpacity': 0.1}).add_to(m)
        folium.GeoJson(roads, name='โครงข่ายถนน',
                       style_function=lambda x: {'color': '#3388ff', 'weight': 1, 'opacity': 0.4}).add_to(m)

        # 4. ปักหมุดเฉพาะ Top 10
        for i, (idx, row) in enumerate(top_10_hotspots.iterrows()):
            popup_text = f"""
            <div style="font-family: Tahoma; font-size: 12px; width: 180px;">
                <b>อันดับที่ {i+1}</b><br>
                จำนวนเหตุการณ์: {int(row['count'])} ครั้ง<br>
                สาเหตุหลัก: {row['top_cause']}
            </div>
            """
            folium.Marker(
                location=[row['LATITUDE'], row['LONGITUDE']],
                popup=folium.Popup(popup_text, max_width=200),
                icon=folium.Icon(color='red', icon='exclamation', prefix='fa')
            ).add_to(m)

        # แสดงแผนที่
        st_folium(m, width="100%", height=650)

    with col_info:
        st.subheader("🏆 Top 10 จุดอันตราย")
        for i, (idx, row) in enumerate(top_10_hotspots.iterrows()):
            with st.expander(f"อันดับ {i+1} — {int(row['count'])} ครั้ง"):
                st.write(f"🚘 **รถคันหลัก:** {row['top_vehicle']}")
                st.write(f"⚠️ **สาเหตุหลัก:** {row['top_cause']}")
                st.write(f"📍 **พิกัด:** {row['LATITUDE']:.4f}, {row['LONGITUDE']:.4f}")

except Exception as e:
    st.error(f"❌ เกิดข้อผิดพลาด: {e}")
    st.info("กรุณาตรวจสอบว่าไฟล์ข้อมูล (.csv และ .zip) อัปโหลดขึ้น GitHub ครบถ้วนแล้ว")
